# Text Scraping 1 - Using HTML

## BeautifulSoup

## Crawling (banyak pages)

Algorithm:

1. tentukan alamat url yang akan di store (tanpa page number)
2. buat array kosong sesuai dengan jumlah feature yang akan dimasukkan
3. buat loop dari page yang akan diambil
4. append terhadap array dari setiap tag

In [25]:
from bs4 import BeautifulSoup
import requests

root = 'https://www.linkedin.com/jobs/search/?distance=25.0&geoId=102478259&keywords=data%20analysis&origin=HISTORY&start='

job_name = []
loc = []
company = []
jobLink = []

for page in range(0, 250, 25):
  url = requests.get(root + str(page))
  soup = BeautifulSoup(url.text, 'html.parser')

  for q in soup.find_all('span', {'class': 'sr-only'}):
    if q.text.strip() == 'LinkedIn' or q.text.strip() == 'Expand search':
      continue
    job_name.append(q.text.strip())

  for a in soup.find_all("span", {"class":"job-search-card__location"}):
    loc.append(a.text.strip())

  for t in soup.find_all('a', {"class" :"hidden-nested-link"}):
    company.append(t.text.strip())

  for z in soup.find_all('a'):
    href = z.get('href')  # Ambil nilai atribut href
    if href and "linkedin.com/jobs/view/" in href:
      jobLink.append(href)

In [26]:
len(job_name), len(loc), len(company),len(jobLink)

(120, 120, 120, 120)

In [27]:
import pandas as pd
df = pd.DataFrame(
    {'jobname':job_name,
     'location':loc,
     'company':company,
     'jobLink':jobLink
     })
df
# df['jobLink'][0]

,jobname,location,company,jobLink
0,Corporate Banking Business Analyst,Jakarta Metropolitan Area,PT. BANK NEGARA INDONESIA (Persero) Tbk.,https://id.linkedin.com/jobs/view/corporate-ba...
1,Business Analyst,"Jakarta, Indonesia",OTO,https://id.linkedin.com/jobs/view/business-ana...
2,1,"Lembang, West Java, Indonesia",PT Adaro Energy Indonesia Tbk,https://id.linkedin.com/jobs/view/1-at-pt-adar...
3,Data Analyst Staff,"Jakarta, Indonesia",PT. Surya Pertiwi Tbk,https://id.linkedin.com/jobs/view/data-analyst...
4,Data Analyst Marketing,"Jakarta, Jakarta, Indonesia",PT ASTRA OTOPARTS Tbk,https://id.linkedin.com/jobs/view/data-analyst...
...,...,...,...,...
115,STUDENTS ONLY! 2025 On The Job Training program,"Jakarta, Jakarta, Indonesia",Mövenpick Hotel Jakarta City Centre,https://id.linkedin.com/jobs/view/students-onl...
116,Commercial Data Analyst,"Tangerang, Banten, Indonesia",PT. Softex Indonesia,https://id.linkedin.com/jobs/view/commercial-d...
117,Business Process Improvement Analyst,"West Jakarta, Jakarta, Indonesia",Kawan Lama Group,https://id.linkedin.com/jobs/view/business-pro...
118,"Business Analyst/Associate Consultant, Indonesia","Jakarta, Jakarta, Indonesia",Boston Consulting Group (BCG),https://id.linkedin.com/jobs/view/business-ana...
119,Product Analyst - Product Operations,Jakarta Metropolitan Area,Traveloka,https://id.linkedin.com/jobs/view/product-anal...

In [28]:
df.to_csv('hasilAkhirLinkedIn3.csv',index=False)